version: "3.7"
services:
  postgres_cadastro:
    container_name: postgres_cadastro
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:9.0.2
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"
  artemis_ifood:
    image: vromero/activemq-artemis:2.11.0
    container_name: activemq_ifood
    environment:
        ARTEMIS_USERNAME: user-amq
        ARTEMIS_PASSWORD: password-amq
    ports:
        - "8161:8161"
        - "61616:61616"
  mongodb_ifood:
    image: mongo
    container_name: mongo_ifood
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: pedido
    ports:
      - "27017:27017"